---
- name: sre-web-base
  hosts: localhost
  become: yes
  tasks:
    - name: Disable IPv6
      command:
        cmd: sysctl -w net.ipv6.conf.default.disable_ipv6=1;sysctl -w net.ipv6.conf.all.disable_ipv6=1

    - name: Remove NTP
      ansible.builtin.apt:
        name: ntp
        state: absent

    - name: Install base packages
      ansible.builtin.apt:
        name:
          - chrony
          - mlocate
          - tree
          - htop
          - netcat
          - sysstat
          - python3-pip
          - iptables
          - iptables-persistent
          - ca-certificates
          - curl
        state: present

    - name: Install ansible modules
      ansible.builtin.shell:
        cmd: ansible-galaxy collection install community.docker

    - name: Import and run additional playbooks
      include_tasks: "{{ item }}"
      loop:
        - sre-data-docker.yml
